#
# setup continuous integration to validate the countries dataset and code.
#

language: php

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - npm install -g jsonlint

script:
  - jsonlint -q -c countries.json